import {Dish} from "./Dish";

export const Dishes: Dish[] = [
    {iden: "piz", name:"Pizza",cuisineType:"italian", dishCategory:"main course",ingredients:"flour, cheese, tomato sauce, pepperoni",maxAmountOfDishes: 12, dishDescription:"Everyone loves it. Literally.", priceUSD:13, priceEUR:12, mainPhotoLink:"../../assets/pizza.jpg",secondPhotoLink:"../../assets/pizza2.jpg",thirdPhotoLink:"../../assets/pizza3.jpg"},
    {iden: "pbj", name:"PeanutButter&Jelly",cuisineType:"american", dishCategory:"breakfast",ingredients:"bread, peanut butter, jelly",maxAmountOfDishes: 80, dishDescription:"Great pre-game meal invented by KG himself", priceUSD:8, priceEUR:7, mainPhotoLink:"../../assets/peanutButterJelly.jpg",secondPhotoLink:"../../assets/peanutButterJelly2.jpg",thirdPhotoLink:"../../assets/peanutButterJelly3.jpg"},
    {iden: "hbg", name:"Hamburger",cuisineType:"american", dishCategory:"main course",ingredients:"bread roll, cheese, tomato, beef burger , pickle, onion",maxAmountOfDishes: 30, dishDescription:"Shaq approves", priceUSD:11, priceEUR:9.5, mainPhotoLink:"../../assets/hamburger.jpg",secondPhotoLink:"../../assets/hamburger2.jpg",thirdPhotoLink:"../../assets/hamburger3.jpg"},
    {iden: "cur", name:"Curry Chicken",cuisineType:"indian", dishCategory:"main course",ingredients:"rice, chicken, curry sauce",maxAmountOfDishes: 18, dishDescription:"Nearly as good as the greatest shooter of all time", priceUSD:10, priceEUR:9, mainPhotoLink:"../../assets/curryChicken.jpg",secondPhotoLink:"../../assets/curryChicken2.jpg",thirdPhotoLink:"../../assets/curryChicken3.jpg"},
    {iden: "biw", name:"Beer",cuisineType:"international", dishCategory:"alcohol beverage",ingredients:"beer",maxAmountOfDishes: 100, dishDescription:"A great drink for great people", priceUSD:4, priceEUR:3, mainPhotoLink:"../../assets/beer.jpg",secondPhotoLink:"../../assets/beer2.png",thirdPhotoLink:"../../assets/beer3.jpg"},
    {iden: "gat", name:"Gatorade",cuisineType:"american", dishCategory:"soft beverage",ingredients:"sugar, lots of sugar, water",maxAmountOfDishes: 100, dishDescription:"MJ advertised it, so take one", priceUSD:2.5, priceEUR:2, mainPhotoLink:"../../assets/gatorade.jpg",secondPhotoLink:"../../assets/gatorade2.jpg",thirdPhotoLink:"../../assets/gatorade3.jpg"},
    {iden: "ces", name:"Cesar's Salad",cuisineType:"mediterranean", dishCategory:"main course",ingredients:"salad, grilled chicken , tomatoes, parmesan cheese",maxAmountOfDishes: 20, dishDescription:"Lots of valuable nutrients", priceUSD:7.5, priceEUR:7, mainPhotoLink:"../../assets/cesarsSalad.jpg",secondPhotoLink:"../../assets/cesarsSalad2.jpg",thirdPhotoLink:"../../assets/cesarsSalad3.jpg"},
    {iden: "gub", name:"Gummy Bears",cuisineType:"international", dishCategory:"snack",ingredients:"sugar, gelatin",maxAmountOfDishes: 100, dishDescription:"Derick Roses favourite", priceUSD:1.5, priceEUR:1, mainPhotoLink:"../../assets/gummyBears.jpg", secondPhotoLink:"../../assets/gummyBears2.png",thirdPhotoLink:"../../assets/gummyBears3.jpg"},
    {iden: "scc", name:"Schabowy chop",cuisineType:"polish", dishCategory:"main course",ingredients:"mashed potatoes, pork chop, cabbage salad",maxAmountOfDishes: 5, dishDescription:"Marcin Gortats unique pre-game meal", priceUSD:6, priceEUR:6, mainPhotoLink:"../../assets/schabowy.jpg",secondPhotoLink:"../../assets/schabowy2.jpg",thirdPhotoLink:"../../assets/schabowy3.jpg"},
    {iden: "snd", name:"Sandwich",cuisineType:"international", dishCategory:"snack",ingredients:"bread, lettuce leaf, ham, cheese",maxAmountOfDishes: 50, dishDescription:"your best typical breakfast", priceUSD:3, priceEUR:2, mainPhotoLink:"../../assets/sandwich.jpg",secondPhotoLink:"../../assets/sandwich2.jpg",thirdPhotoLink:"../../assets/sandwich3.jpg"},
    {iden: "pop", name:"Popcorn",cuisineType:"international", dishCategory:"snack",ingredients:"corn",maxAmountOfDishes: 100, dishDescription:"Stephen Curry says the best one is in Dallas, but we think otherwise...", priceUSD:4, priceEUR:4, mainPhotoLink:"../../assets/popcorn.jpg",secondPhotoLink:"../../assets/popcorn2.jpg",thirdPhotoLink:"../../assets/popcorn3.jpg"},
    {iden: "wat", name:"Sparkling Water",cuisineType:"international", dishCategory:"soft beverage",ingredients:"water",maxAmountOfDishes: 100, dishDescription:"The most natural in-game drink", priceUSD:1, priceEUR:1, mainPhotoLink:"../../assets/water.jpg",secondPhotoLink:"../../assets/water2_2.jpg",thirdPhotoLink:"../../assets/water3.jpg"},
    {iden: "ram", name:"Ramen",cuisineType:"japanese", dishCategory:"main course",ingredients:"noodles, panko chicken, sea weed, pickled ginger, egg",maxAmountOfDishes: 15, dishDescription:"Taste as good as it smells, Rui Hachimura confirms.", priceUSD:12, priceEUR:11, mainPhotoLink:"../../assets/ramen.jpg",secondPhotoLink:"../../assets/ramen2.jpg",thirdPhotoLink:"../../assets/ramen3.jpg"},
    {iden: "frg", name:"Frog Wings",cuisineType:"french", dishCategory:"starter",ingredients:"frog meat, salt",maxAmountOfDishes: 5, dishDescription:"Rudy Gobert adores them", priceUSD:7, priceEUR:7, mainPhotoLink:"../../assets/frogLegs.jpg",secondPhotoLink:"../../assets/frogLegs2.jpg",thirdPhotoLink:"../../assets/frogLegs3.jpg"},
    {iden: "keb", name:"Kebab",cuisineType:"turkish", dishCategory:"main course",ingredients:"chicken, cabage, cucumber, hot sauce",maxAmountOfDishes: 45, dishDescription:"Perfect cheat day meal", priceUSD:7.5, priceEUR:6, mainPhotoLink:"../../assets/kebab.jpg",secondPhotoLink:"../../assets/kebab2.jpg",thirdPhotoLink:"../../assets/kebab3.jpg"},
    {iden: "shr", name:"Tiger Shrimps in vine sauce",cuisineType:"international", dishCategory:"main course",ingredients:"tiger shrimps, rolls, vine sauce, chilli peppers",maxAmountOfDishes: 8, dishDescription:"Chefs special", priceUSD:24, priceEUR:23, mainPhotoLink:"../../assets/shrimps.jpg",secondPhotoLink:"../../assets/shrimps2.jpg",thirdPhotoLink:"../../assets/shrimps3.jpg"},
];
